"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from typing import List, Optional
from venariai import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class ColorWeights:
    color_name: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('color_name') }})
    weight: float = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('weight') }})
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class Upcs:
    size: float = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('size') }})
    upc: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('upc') }})
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class Product:
    age_group: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('age_group') }})
    brand_name: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('brand_name') }})
    cat1: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('cat1') }})
    color_weights: List[ColorWeights] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('color_weights') }})
    gender: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('gender') }})
    image: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('image') }})
    product_id: float = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('product_id') }})
    product_title: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('product_title') }})
    style_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('style_id') }})
    upcs: List[Upcs] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('upcs') }})
    cat2: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('cat2') }})
    cat3: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('cat3') }})
    cat4: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('cat4') }})
    colorway: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('colorway') }})
    designer: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('designer') }})
    release_date: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('release_date') }})
    shaft_style: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('shaft_style') }})
    silhouette: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('silhouette') }})
    upper_material: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('upper_material') }})
    

