"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from dataclasses_json import Undefined, dataclass_json
from typing import Optional
from venariai import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class SneakerIDBatchAsyncResponseBody:
    r"""Successfully queued inference"""
    id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('id') }})
    internal_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('internal_id') }})
    



@dataclasses.dataclass
class SneakerIDBatchAsyncResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    object: Optional[SneakerIDBatchAsyncResponseBody] = dataclasses.field(default=None)
    r"""Successfully queued inference"""
    

